format:
  date: dd.MM.yy

application:
  version: 1.0

spring:
  application.name: demo-sales-service

  # SQL Server
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=sales
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123

  # MySQL
  #datasource:
  #  url: jdbc:mysql://localhost:3306/sales
  #  driverClassName: com.mysql.jdbc.Driver
  #  username: sa
  #  password: 123

  jpa:
    show-sql: false #true
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080